
UPDATE faqs SET answer_html = '<p>At <a href="/">Holis Wellness Center</a>, we offer a full range of signature and traditional <a href="/treatments-therapies">spa treatments</a>, including: <a href="/treatments-therapies">Massages</a>, <a href="/treatments-therapies">Holistic Facials</a>, and <a href="/treatments-therapies">Body Treatments</a>.</p><p>We also specialize in <a href="/treatments-therapies">holistic therapies</a> such as Craniosacral Therapy, Osteopathy, Breathwork, and Acupuncture.</p><p>Our <a href="/classes/schedule">daily movement classes</a> include: Yoga, Pilates, Aerial Yoga, Sound Healing, and Gyrotonic, plus <a href="/private-sessions">private sessions</a>.</p><p>For a deeper experience, we partner with trusted local providers to offer <a href="/retreats">Day Retreats</a> and fully customized <a href="/retreats">Multi-Day Retreats</a>.</p>' WHERE question = 'What services do you offer?';

UPDATE faqs SET answer_html = '<p>We''re based in <strong>Manuel Antonio, Quepos, Costa Rica</strong>, surrounded by lush rainforest and overlooking the Pacific Ocean. It''s just a 2.5–3 hour scenic drive from <strong>San José International Airport</strong>.</p>' WHERE question = 'Where are you located?';

UPDATE faqs SET answer_html = '<p>Yes. Our <a href="/treatments-therapies">signature therapies</a> are popular, and <strong>sessions fill up fast</strong>, so we recommend <strong>booking ahead</strong> to secure your spot.</p><ul><li><strong>Spa services, therapies & private classes:</strong> Please book at least <strong>24 hours</strong> in advance.</li><li><strong>Day retreats & multi-day retreats:</strong> Please book at least <strong>48 hours</strong> in advance.</li><li><strong>Studio classes:</strong> Walk-ins are welcome, but we recommend reserving to secure your spot.</li></ul>' WHERE question = 'Do I need to book in advance?';

UPDATE faqs SET answer_html = '<p>Yes! Enjoy <a href="/private-sessions">private sessions</a> at our studio or in the comfort of your rental villa. Group classes are also available as <strong>single sessions, class packs,</strong> or <strong>unlimited passes</strong>.</p>' WHERE question = 'Do you offer private classes?';

UPDATE faqs SET answer_html = '<p>Yes. We proudly use food-grade, organic products, including:</p><ul><li><strong>Essenthya Skincare Food</strong> – created by our founder, <a href="/about">Evelina Bolognini</a></li><li><strong>Biosfera</strong> – award-winning skincare line made in Costa Rica</li></ul>' WHERE question = 'Are your spa products natural or organic?';

UPDATE faqs SET answer_html = '<p>All experiences are designed by <a href="/about">Evelina Bolognini</a>, founder of Holis Wellness Center, with the goal of sharing the best of Manuel Antonio''s natural beauty and healing traditions.</p>' WHERE question = 'Who leads your wellness experiences?';
