
DELETE FROM faqs;
INSERT INTO faqs (category_id, question, answer_html, sort_order, is_visible) VALUES
('1cdb01a8-6951-4051-a181-489513ae8547', 'What services do you offer?', '<p>At <a href="https://www.spaholis.com/home">Holis Wellness Center</a>, we offer a full range of signature and traditional <a href="https://www.spaholis.com/spa">spa treatments</a>, including: <a href="https://www.spaholis.com/spa#massages">Massages</a>, <a href="https://www.spaholis.com/spa#facials">Holistic Facials</a>, and <a href="https://www.spaholis.com/spa#body-treatments">Body Treatments</a>.</p><p>We also specialize in <a href="https://www.spaholis.com/holistic-therapy">holistic therapies</a> such as <a href="https://www.spaholis.com/holistic-therapy#craniosacral-therapy">Craniosacral Therapy</a>, <a href="https://www.spaholis.com/holistic-therapy#osteopathy">Osteopathy</a>, <a href="https://www.spaholis.com/holistic-therapy#niyama-breathwork">Breathwork</a>, and <a href="https://www.spaholis.com/holistic-therapy#cupping">Acupuncture</a>.</p><p>Our <a href="https://www.spaholis.com/class-schedule">daily movement classes</a> include: Yoga, Pilates, Aerial Yoga, Sound Healing, and Gyrotonic, plus <a href="https://www.spaholis.com/private-classes">private sessions</a>.</p><p>For a deeper experience, we partner with trusted local providers to offer <a href="https://www.spaholis.com/wellness-programs">Day Retreats</a> and fully customized <a href="https://www.spaholis.com/wellness-retreats-manuel-antonio">Multi-Day Retreats</a>.</p>', 1, true),
('1cdb01a8-6951-4051-a181-489513ae8547', 'Where are you located?', '<p>We''re based in <strong>Manuel Antonio, Quepos, Costa Rica</strong>, surrounded by lush rainforest and overlooking the Pacific Ocean. It''s just a 2.5–3 hour scenic drive from <strong>San José International Airport</strong>. <a href="https://maps.app.goo.gl/mvHQ9VCfRJoW1ykW8">View us on Google Maps</a></p>', 2, true),
('1cdb01a8-6951-4051-a181-489513ae8547', 'Do I need to book in advance?', '<p>Yes. Our <a href="https://www.spaholis.com/spa">signature therapies</a> are popular, and <strong>sessions fill up fast</strong>, so we recommend <strong>booking ahead</strong> to secure your spot.</p><ul><li><strong>Spa services, therapies & private classes:</strong> Please book at least <strong>24 hours</strong> in advance.</li><li><strong>Day retreats & multi-day retreats:</strong> Please book at least <strong>48 hours</strong> in advance.</li><li><strong>Studio classes:</strong> Walk-ins are welcome, but we recommend reserving to secure your spot.</li></ul>', 3, true),
('1cdb01a8-6951-4051-a181-489513ae8547', 'Do you offer private classes?', '<p>Yes! Enjoy <a href="https://www.spaholis.com/private-classes">private sessions</a> at our studio or in the comfort of your rental villa. Group classes are also available as <strong>single sessions, class packs,</strong> or <strong>unlimited passes</strong>.</p>', 4, true),
('1cdb01a8-6951-4051-a181-489513ae8547', 'Are your spa products natural or organic?', '<p>Yes. We proudly use food-grade, organic products, including:</p><ul><li><strong>Essenthya Skincare Food</strong> – created by our founder, <a href="https://www.spaholis.com/evelina-bolognini">Evelina Bolognini</a></li><li><strong>Biosfera</strong> – award-winning skincare line made in Costa Rica</li></ul>', 5, true),
('1cdb01a8-6951-4051-a181-489513ae8547', 'Who leads your wellness experiences?', '<p>All experiences are designed by <a href="https://www.spaholis.com/evelina-bolognini">Evelina Bolognini</a>, founder of Holis Wellness Center, with the goal of sharing the best of Manuel Antonio''s natural beauty and healing traditions.</p>', 6, true),
('1cdb01a8-6951-4051-a181-489513ae8547', 'Do you welcome solo travelers?', '<p>Absolutely! Many of our guests come solo and find our space warm, inclusive, and safe — perfect for connecting with yourself and with like-minded travelers.</p>', 7, true),
('1cdb01a8-6951-4051-a181-489513ae8547', 'What kinds of retreats do you offer?', '<p>We create <strong>private, curated retreats</strong> (typically 5–6 days) that combine:</p><ul><li>Studio classes</li><li>Local adventures</li><li>Holistic therapies</li><li>Delicious, nourishing food</li></ul><p>Every retreat is <strong>100% customized</strong> to your needs.</p>', 8, true),
('1cdb01a8-6951-4051-a181-489513ae8547', 'Can you help with airport transfers and logistics?', '<p>Yes. While transfers aren''t included in all packages, we''re happy to arrange:</p><ul><li>Local transportation</li><li>Airport pickup</li><li>Travel safety tips</li></ul>', 9, true),
('1cdb01a8-6951-4051-a181-489513ae8547', 'Can I book a shorter stay or customize my retreat?', '<p>Definitely! From the length of your stay to the activities and treatments, we can tailor your experience so it''s exactly what you''re looking for.</p>', 10, true);
